<h1>Push Notification</h1>


<div class="list-group">
    <?php foreach ($this->pushNotifications as $pushNotification): ?>
        <li class="list-group-item d-flex justify-content-between align-items-center">
            <h4 class="list-group-item-heading">
                <?= $pushNotification->getTitle() ?>

            </h4>
            <div style="width: 80px">
                <span class="badge badge-primary badge-pill">
   <i class="bi bi-alarm-fill"></i>
                </span>
                <span class="badge badge-primary badge-pill">1</span>
                <span class="badge badge-primary badge-pill">1</span>
            </div>
        </li>

    <?php endforeach ?>
</div>

<div class="btn-group" role="group" aria-label="Post actions">
    <a class="btn btn-primary" href="#">Add new push notification service</a>
</div>