<h1>Push Notification</h1>

<div class="list-group">
    <?php foreach ($this->pushNotifications as $pushNotification): ?>
        <div class="list-group-item">
            <h4 class="list-group-item-heading">
                  <?= $pushNotification->getKey() ?>

            </h4>


        </div>
    <?php endforeach ?>
</div>

<div class="btn-group" role="group" aria-label="Post actions">
    <a class="btn btn-primary" href="#">Add new push notification service</a>
</div>