<?php
$this->headTitle('Device')->setSeparator(' - ')->setAutoEscape(false);
///TODO: move to local
$this->headLink()->prependStylesheet("https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css");
?>
<style>
    .w80 {
        width: 80px;
    }
</style>
<div class="  pr-3">
    <div class="row">
        <div class="col-sm">

            <h1>
                Devices
            </h1>
        </div>
        <div class=" float-right">
             <span class="">

                    <div class="btn-group" role="group" aria-label="Post actions">
                        <a class="btn btn-primary" href="#">Register new device</a>
                    </div>
                </span>
        </div>
    </div>
</div>
<div class="list-group">
    <?php foreach ($this->devices as $device): ?>
        <li class="list-group-item d-flex justify-content-between align-items-center">
            <h4 class="list-group-item-heading">
                <?= $device->getOs() ?> - <?=$device->getVersion()?>

            </h4>
            <div class="w80">
                <span class="  ">
                   <i class="bi bi-pencil-square"></i>
                </span>
                <span class="  ">
                   <i class="bi bi-journal-richtext"></i>
                </span>
                <span class="  ">
                  <i class="bi bi-trash"></i>
                </span>

            </div>
        </li>

    <?php endforeach ?>
</div>
